name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 
    env:
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      EC2_URL: ${{ secrets.EC2_URL }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Verify Docker Hub Login
      - name: Verify Docker Hub Login
        run: |
          echo "Logged in as ${{ secrets.DOCKER_USERNAME }}"
          docker info --format '{{.RegistryConfig.IndexConfigs.docker.io.Secure}}' || echo "Login check failed"
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} && echo "Manual login test succeeded" || echo "Manual login test failed"

      # Step 4: Debug Docker Configuration
      - name: Debug Docker Info
        run: |
          docker info --format '{{json .}}'
          docker version
          echo "Target repository: ${{ secrets.DOCKER_USERNAME }}/disstrikt-backend:latest"

      # Step 5: Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/disstrikt-backend:latest
          load: false
          no-cache: false
          pull: false
        env:
          ACTIONS_STEP_DEBUG: true
          ACTIONS_RUNNER_DEBUG: true

      # Step 6: Setup SSH for EC2
      - name: Setup SSH for EC2
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_URL: ${{ secrets.EC2_URL }}

      # Step 7: Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_URL }} << 'ENDSSH'
            set -e
            echo 'Cleaning up EC2 instance...'
            docker image prune -f || { echo 'Docker image prune failed'; exit 1; }
            if ! command -v docker &> /dev/null
            then 
              sudo apt-get update
              sudo apt-get install -y docker.io
            fi
            echo 'Pulling Docker image...'
            docker pull ${{ secrets.DOCKER_USERNAME }}/disstrikt-backend:latest || { echo 'Docker pull failed'; exit 1; }
            echo 'Stopping existing container...'
            docker stop disstrikt-backend || true 
            docker rm disstrikt-backend || true
            echo 'Running new container...'
            docker run -d -p 8000:8000 --name disstrikt-backend \
              -e MONGO_URL='${{ secrets.MONGO_URL }}' \
              -e PORT='${{ secrets.PORT }}' \
              -e NEXT_PUBLIC_APP_URL='${{ secrets.NEXT_PUBLIC_APP_URL }}' \
              -e RESEND_API_KEY='${{ secrets.RESEND_API_KEY }}' \
              -e COMPANY_RESEND_GMAIL_ACCOUNT='${{ secrets.COMPANY_RESEND_GMAIL_ACCOUNT }}' \
              -e ACCOUNTSID='${{ secrets.ACCOUNTSID }}' \
              -e AUTHTOKEN='${{ secrets.AUTHTOKEN }}' \
              -e FROMPHONENUMBER='${{ secrets.FROMPHONENUMBER }}' \
              -e STRIPE_SECRET_KEY='${{ secrets.STRIPE_SECRET_KEY }}' \
              -e STRIPE_WEBHOOK_SECRET='${{ secrets.STRIPE_WEBHOOK_SECRET }}' \
              -e AUTH_SECRET='${{ secrets.AUTH_SECRET }}' \
              -e JWT_SALT='${{ secrets.JWT_SALT }}' \
              -e GOOGLE_CLIENT_ID='${{ secrets.GOOGLE_CLIENT_ID }}' \
              -e GOOGLE_CLIENT_ID_IOS='${{ secrets.GOOGLE_CLIENT_ID_IOS }}' \
              -e FIREBASE_SERVICE_ACCOUNT='${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' \
              -e GOOGLE_CLIENT_EMAIL='${{ secrets.GOOGLE_CLIENT_EMAIL }}' \
              -e GOOGLE_PROJECT_ID='${{ secrets.GOOGLE_PROJECT_ID }}' \
              -e GOOGLE_PRIVATE_KEY2='${{ secrets.GOOGLE_PRIVATE_KEY2 }}' \
              -e AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}' \
              -e AWS_REGION='${{ secrets.AWS_REGION }}' \
              -e AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
              -e AWS_BUCKET_NAME='${{ secrets.AWS_BUCKET_NAME }}' \
              ${{ secrets.DOCKER_USERNAME }}/disstrikt-backend:latest || { echo 'Docker run failed'; exit 1; }
            echo 'Container running successfully'
            echo "Cleaning up unused Docker resources..."
            docker system prune -af --volumes || { echo "Docker system prune failed"; exit 1; }
            echo "Cleaning up temporary files and logs..."
            sudo rm -rf /tmp/*
            sudo truncate -s 0 /var/log/*.log
            echo "Cleaning up log files..."
            sudo find /var/log/ -type f -name "*.log" -exec truncate -s 0 {} \;
            echo "Checking disk usage after cleanup..."
            df -h
          ENDSSH